### ISSUE TITLE
Add me to the team, please! 

### ISSUE THREAD

**Issue by paula-st** [fablabbcn/employees-info#1]
Hi admin!

I am Paula, could you please add me to the team? 

Thanks :)

Paula

**Comment by viktorsmari** [comment]
**Done!**
 Welcome :smile:

**Comment by paula-st** [comment]
Thanks, Viktor!

Have a nice day,

Paula

**Comment by viktorsmari** [comment]
Can you maybe also add a profile picture?
Thanks!
